config/routes.rb
Depot::Application.routes.draw do
  get "admin" => 'admin#index'
  controller :sessions do
    get     'login' => :new
    post    'login' => :create
    delete  'logout' => :destroy
  end

  resources :users
  resources :pay_types

  get "store/index"
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :carts
    resources :line_items do
      post 'decrement', on: :member
    end  
    root 'store#index', as: 'store', via: :all
  end

  

end

app/controllers/pay_types_controller.rb
class PayTypesController < ApplicationController
  include CurrentCart
  before_action :set_pay_type, only: [:show, :edit, :update, :destroy]
  before_action :set_cart
  # GET /pay_types
  # GET /pay_types.json
  def index
    @pay_types = PayType.all
  end

  # GET /pay_types/1
  # GET /pay_types/1.json
  def show
  end

  # GET /pay_types/new
  def new
    @pay_type = PayType.new
  end

  # GET /pay_types/1/edit
  def edit
  end

  # POST /pay_types
  # POST /pay_types.json
  def create
    @pay_type = PayType.new(pay_type_params)

    respond_to do |format|
      if @pay_type.save
        format.html { redirect_to @pay_type, notice: 'Pay type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pay_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @pay_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pay_types/1
  # PATCH/PUT /pay_types/1.json
  def update
    respond_to do |format|
      if @pay_type.update(pay_type_params)
        format.html { redirect_to @pay_type, notice: 'Pay type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pay_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pay_types/1
  # DELETE /pay_types/1.json
  def destroy
    @pay_type.destroy
    respond_to do |format|
      format.html { redirect_to pay_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pay_type
      @pay_type = PayType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pay_type_params
      params.require(:pay_type).permit(:name)
    end
end

app/helpers/pay_types_helper.rb
module PayTypesHelper
end

app/views/pay_types/_form.html.erb
<%= form_for(@pay_type) do |f| %>
  <% if @pay_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pay_type.errors.count, "error") %> prohibited this pay_type from being saved:</h2>

      <ul>
      <% @pay_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pay_types/edit.html.erb
<h1>Editing pay_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @pay_type %> |
<%= link_to 'Back', pay_types_path %>

app/views/pay_types/index.html.erb
<h1>Listing pay_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pay_types.each do |pay_type| %>
      <tr>
        <td><%= pay_type.name %></td>
        <td><%= link_to 'Show', pay_type %></td>
        <td><%= link_to 'Edit', edit_pay_type_path(pay_type) %></td>
        <td><%= link_to 'Destroy', pay_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pay type', new_pay_type_path %>

app/views/pay_types/new.html.erb
<h1>New pay_type</h1>

<%= render 'form' %>

<%= link_to 'Back', pay_types_path %>

app/views/pay_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pay_type.name %>
</p>

<%= link_to 'Edit', edit_pay_type_path(@pay_type) %> |
<%= link_to 'Back', pay_types_path %>